### ISSUE TITLE
Question: Refetching paginated resource after mutation

### ISSUE THREAD

**Issue by saaymeen** [data-client/rest-hooks#1548]
Hi!

I display a paginated result from `useResource` at one point in my app. The user can create additional items for this list in a dialog. The docs for [immediate mutation updates](https://resthooks.io/docs/guides/immediate-updates) specify pretty well how to append the result of a mutation in the current cache, for my use case however this does not work because I do not know the pagination params of the list in the create dialog. (This would be impossible to know anyway, since there can be essentially an unknown number of lists of that resource across the app)
Appending the created resource to the paginated list does make little sense, since I can't easily figure out if the new resource matches the pagination criteria. But one way to have a immediate UI update would be to refetch all `useResource` hooks that use the detail shape, no matter their params. `invalidate` and `fetch` only trigger a change for hooks that use the same params, is the a way to tell them to refetch for every set of params that are currently being rendered? Or am I overthinking something/am I looking at this from the wrong angle?

I could not find a discussion forum for the project, sorry for posting this question as an issue.

Kind regards

Simon

**Comment by stufisher** [comment]
@ntucker i'm interested in this one too.

We have for example a Resource. In the current view are two `getList`s with different query params (pagination, filter, etc). Then we create a new entity within the same view. I'd like to be able to trigger re-fetch of these two lists to which the new entity may or may not apply. 

I also have a second use case where this sort of functionality would be triggered from a websocket message too (i think i can use a manager to do this, assuming we can refresh a resource regardless of its query params)

**Comment by ntucker** [comment]
We could have `Controller.invalidateAll(key => matches);`

Where it checks each key and if it matches will invalidate that endpoint. For RestEndpoints this could use path-to-regex to autobuild the matcher, making it `Controller.invalidateAll(MyEndpoint.matchAll);`

**Comment by stufisher** [comment]
Sounds like that would work for me 👍

**Comment by ntucker** [comment]
@stufisher https://resthooks.io/docs/api/Controller#invalidateAll latest release has this

**Comment by stufisher** [comment]
Much appreciated, ill try and give this a go this week. Thanks!

**Comment by ntucker** [comment]
Next step to covering more uses cases better is [Collections](https://github.com/data-client/rest-hooks/discussions/2566). Please review if interested in this use case!

**Comment by ntucker** [comment]
[Collections](https://github.com/data-client/rest-hooks/pull/2593) are the true solution and will be released soon!
