### ISSUE TITLE
RFC: Retry on 'soft' errors + sideEffect false

### ISSUE THREAD

**Issue by ntucker** [data-client/rest-hooks#2292]
## Mechanics

Endpoints with sideEffects are not safe to retry, as it cannot be guaranteed where they failed - which means issuing them multiple times could result in undesirable effects!

'hard' errors indicate they should not be ignored. Most commonly this indicates there is a real problem that won't be fixed by refetching - for instance if the fetch is not authorized. In these cases, retrying would simply delay the inevitable.

'soft' errors on the other hand often indicate transient issues like a flaky wifi connection.

## Implementation

- Add retryPolicy to ExtendedEndpointOptions.
  - e.g., `(retry, { error, count }) => setTimeout(retry, 20)`
- NetworkManager to schedule retries on soft errors
- Provide policy generator method (number of retries, backoff period, handle offline/online)
- RestEndpoint to do one retry after 40ms; and do native/web feature detection for online/offline support

### Due to network offline

```ts
const retryPolicy = (retry, { error, count }) => {
  if (error.becauseOffline) {
    if (navigator.onLine) { retry(); }
    window.addEventListener('online', () => { retry() });
  }
  if (count < 2) setTimeout(retry, 10);
}
```

If something is being retried - it must be considered 'in flight' for network manager

**Comment by ntucker** [comment]
@notwillk

**Comment by notwillk** [comment]
I'm @notwillk and I approve this message

**Comment by ntucker** [comment]
Closing in favor of discussion: https://github.com/data-client/rest-hooks/discussions/2401
