### ISSUE TITLE
useLoading is incompatible with React.StrictMode

### ISSUE THREAD

**Issue by d7sd6u** [data-client/rest-hooks#2484]
**React version** - 18.2.0

**TypeScript version** - 4.9.3

**@rest-hooks/hooks version** - 3.1.10

**Package manager version** - pnpm

**Environment version** - firefox 110

When using `React.StrictMode` `useLoading` hook never changes loading state.

**To Reproduce**
1. Use `useLoading` in component inside a tree wrapped with `React.StrictMode`
2. Trigger async function
3. Loading state never updates (keeps "loading" after async function have resolved)

**Expected behavior**
`useLoading` works the same with React.StrictMode as without it.

**Additional context**
Issue may be solved by changing useEffect callback inside useLoading implementation (`packages/hooks/src/useLoading.ts`)  from:
```typescript
useEffect(
  () => () => {
    isMountedRef.current = false;
  },
  [],
);
```
to:
```typescript
useEffect(
  () => {
    isMountedRef.current = true;
    return () => {
      isMountedRef.current = false;
    }
  },
  [],
);
```

**Comment by ntucker** [comment]
Fixed in https://github.com/data-client/rest-hooks/releases/tag/%40rest-hooks%2Fhooks%403.1.12

Thanks for the report!
